# Generated by Django 3.0.10 on 2021-05-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azureex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('연번', models.FloatField(blank=True, null=True)),
                ('종류', models.CharField(blank=True, max_length=255, null=True)),
                ('종별', models.CharField(blank=True, max_length=255, null=True)),
                ('지정번호', models.CharField(blank=True, max_length=255, null=True)),
                ('지정일자', models.DateTimeField(blank=True, null=True)),
                ('문화재명', models.CharField(blank=True, max_length=255, null=True)),
                ('소재지', models.CharField(blank=True, max_length=255, null=True)),
                ('관리주체', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'azureex$',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
    ]
